services:

  #prometheus监控 — Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      - ./build/prometheus/server/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=10GB'
    restart: always
    user: root
    ports:
      - "9090:9090"
    networks:
      - chatgpt-wechat_network

  #查看prometheus监控数据 - Grafana to view Prometheus monitoring data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    user: root
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    restart: always
    volumes:
        - ./data/grafana/data:/var/lib/grafana
    ports:
        - "8891:3000"
    networks:
        - chatgpt-wechat_network
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    volumes:
      - ./build/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./build/alertmanager/data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--cluster.advertise-address=alertmanager:9093'
    ports:
      - "9093:9093"
    networks:
      - chatgpt-wechat_network
    restart: always
networks:
  chatgpt-wechat_network:
    external: true

