// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"base/application/service"
	"base/infrastructure/svc"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeVersionService 初始化版本服务
func InitializeNoticeService(svcCtx *svc.ServiceContext) *service.NoticeService {
	smsInterface := ProviderMessageService(svcCtx)
	mailInterface := ProviderMailService(svcCtx)
	noticeService := ProviderNoticeService(svcCtx, smsInterface, mailInterface)
	return noticeService
}

// wire.go:

// providerSet 定义用户服务相关的依赖提供者
var providerSet = wire.NewSet(

	ServiceProviderSet,
)
